# Generated by Django 3.0.8 on 2020-07-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcuser',
            name='useremail',
        ),
    ]
